### ISSUE TITLE
현재 태깅된 정보를 업데이트 후 새롭게 저장해도 업데이트 되지 않는것 같음.

### ISSUE THREAD

**Issue by kmu-leeky** [kmu-leeky/crc-research#10]
태깅 후 저장 (apple 로 했다고 가정)
수정 버튼 후 pizza 선택 후 저장.
다시 선택된 태그에 마우스를 올려두면 apple 이 보임.

**Comment by oryondark** [comment]
Update 작업 완료.
--------------------------------------------------------
이슈1.
현재 Update 후 기존의 데이터가 삭제되지 않으며, 새롭게 업데이트 되는 데이터는 해당 Tag 이름의 JSON파일로 append됩니다.

교수님. 
현재 Update 작업을 수행 시, Update 전 데이터 정보를 받아오도록 일부 작업을 수행하였는데요.
JSON 파일도 수정하도록 할까요?

**Comment by kmu-leeky** [comment]
오케이.
현재 사이트에서는 새로운게 보이는데, 결과물 json 은 계속 남아있다는 얘기지?
즉 같은 파일 이름으로 여러개의 태그가 존재 가능할 수 있는.
그렇다면 지금은 그대로 두자. 어짜피 sequential 하게 append 될테고 맨 마지막게 유효한 기록이 될테니.
혹시 모르니, json 필드의 timestamp 를 추가하는건 어떨까? 저장된 시간을 저장.

**Comment by oryondark** [comment]
TimeStamp 구현
----------------------------
Json에 timestamp를 추가하였습니다.

Issue
----------
UTC second로 변경하도록 하겠습니다.
