### ISSUE TITLE
여러 이미지 파일을 불러와서 순차적으로 작업하는 기능 구현

### ISSUE THREAD

**Issue by kmu-leeky** [kmu-leeky/crc-research#14]
현재 시스템은 하나의 이미지만 보여주며 작업하고 있음.
디렉토리에 저장되어 있는 많은 이미지를 불러와서 작업 및 저장하는 환경 구축.
본 이슈에서는 전반적인 아이디어를 작성하고 세부 구현 내용은  별도의 이슈를 생성.

**Comment by oryondark** [comment]
네 교수님.
우선 계획을 오전까지 정리한 후 오후 쯤 이슈에 계획을 작성해보겠습니다.

**Comment by kmu-leeky** [comment]
오케이.

먼저 전체 사진들에 대해서 작업하는 방법에서 thumbnail 방법이 많이 어렵지 않다면 (약간의 시간이 더 걸린다면) 그렇게 하면 좋을것 같아.

서버 부분도 잘 언급했네. 최소한의 정보는 데이터 베이스에 저장해야 할것 같기는 하다.
서버의 경우에는 우선은 구현이 쉬울것 같은 distributed server 가 어떨까 싶네.
그런데 별도로 서버를 구축하는것도 만만치 않은 일이 될것 같으니
그냥 dynamodb 를 사용해보면 어떨까? 단순히 key-value 를 저장하는것이니
다른 부가적인 걸 신경 안써도 되서 더 나을수도 있을것 같아.

**Comment by oryondark** [comment]
네 교수님.

각각 서로 다른 Image들로 저장된 서버들을 구성하고, 
각 작업 상태 관리를 AWS DynamoDB를 이용할 경우 별도의 DB 서버를 구축할 번거로움도 없을 것 같으며, 
Key-Value로 저장하기 때문에 좋을 것 같습니다.

순차적 작업 기능은 위 방법으로 진행하겠습니다.

**Comment by oryondark** [comment]
>네 교수님.
DynamoDB의 Key-Value를 이용하여 접근하면, **환경이 구축된 하나의 Server Local에 많은 Image를 저장 한 후, 작업자 별로 주어진 Key 정보를 이용하여 Load할 수 있는 Image를 제한하는 방법**이 새로 서버를 구축해야하는 번거로움이 없어 좋을 것 같습니다.

### 간단하게 생각해본 Image load 방법

| Key | Value |
|----------|----------|
| employee_1      | "imageName" ,  "imageUrl" , "done" , "etc"
| employee_2      | "imageName" ,  "imageUrl" , "done" , "etc"
| employee_3      | "imageName" ,  "imageUrl" , "done" , "etc"

> DynamoDB를 이용할 경우 관리가 필요한 추가 정보의 저장 및 AWS API 연동과 같은 AWS Service 사용  **기능 확장에 번거로움이 최소화 될 수 있을 것 같습니다.**

**Comment by oryondark** [comment]
## 작업 순서
다음 작업 순서는 아래와 같이 진행하겠습니다.

1. #17 Selection List를 구현
2. #15 DynamoDB 구축을 진행하고, Json을 주기적으로 압축하여 S3로 Upload
3. #16 Done Button 생성하고, 클릭 시 DynamoDB로 Update하여 Selection List에서 Done = False 항목만 따로 관리할 수 있도록 구현


개발 진행 중 발생하는 이슈 등은 해당 이슈 쪽으로 업데이트하겠습니다.

**Comment by kmu-leeky** [comment]
오케이. 잘 정리했다. #15 를 dynamodb 구축과 JSON 의 주기적인 백업 to S3 로 업데이트 한 후에 이번 이슈는 close 해도 되겠다.
