### ISSUE TITLE
AWS DynamoDB 구축 및 연동

### ISSUE THREAD

**Issue by oryondark** [kmu-leeky/crc-research#15]
1. 작업자 별로 분산된 Image가 저장된 Server를 배정하고, 작업자가 사용하는 Host Name을 Key를 사용하여 DB에 접근이 가능하도록 구현

| Key |      Value      | 
|----------|:-------------:|
| HostName_1 | {"Done":"True", "LocalUrl":"Image location" } | 
| HostName_2 | {"Done":"False", "LocalUrl":"Image location"} |
| HostName_3 | {"Done":"True", "LocalUrl":"Image location" } |

**Comment by kmu-leeky** [comment]
JSON 파일의 주기적인 S3 로의 백업은 별도의 이슈로 만드는게 트래킹측면에서 더 나을것 같아.

**Comment by oryondark** [comment]
네 교수님 ~ JSON 파일 백업은 별도의 이슈로 만들어두겠습니다.
