### ISSUE TITLE
Thumbnail 클릭 시 Preview 이미지 로드

### ISSUE THREAD

**Issue by oryondark** [kmu-leeky/crc-research#20]

**Comment by oryondark** [comment]
### 작업현황
1. 현재 제공받은 샘플이미지를 Thumbnail로 Load한 후, 각 이미지 클릭 시 작업을 위한 Preview 이미지로 Load

### Issue
한 번 Load했던 이미지를 다시 Load할 경우 오류가 발생하고 있어 확인 중에 있습니다.

**Comment by kmu-leeky** [comment]
오케이. 잘 확인함.

**Comment by oryondark** [comment]
주소가 변경되었습니다.
https://s3-ap-northeast-1.amazonaws.com/kmu-serverless-annotorious-hosting/main.html

웹 페이지 접속 시 자동으로 썸네일 로드되도록 구현

**Comment by oryondark** [comment]
### 이슈 해결
한 번 Load했던 이미지를 다시 Load할 경우 발생하는 오류를 해결했습니다.
