### ISSUE TITLE
Cropped Image List Page 

### ISSUE THREAD

**Issue by oryondark** [kmu-leeky/crc-research#26]
추출한 이미지들을 볼 수 있는 페이지 작성

작업 순서:

1. 각 특징별로 모아서 볼 수 있도록 작성하기

**Comment by oryondark** [comment]
### 작업 상황
Page CSS 작업 및 Cropped 이미지 List 확인 가능한 페이지 구현.

http://ec2-52-78-38-67.ap-northeast-2.compute.amazonaws.com

교수님 본 과제에서 서버리스 구축은 중요하지 않다면, 과제 해결을 위한 주소는 위  주소로하고,
논문을 위한 서버리스는 따로 이슈관리 해도될까요?.

-----------------

![image](https://user-images.githubusercontent.com/35071931/40222773-9ef681ac-5abb-11e8-828b-4a14d46250ab.png)

![image](https://user-images.githubusercontent.com/35071931/40222809-bcfbd15c-5abb-11e8-988d-2f71cef454a7.png)


### 이슈
1. CSS 조정이 필요합니다.

**Comment by kmu-leeky** [comment]
오늘 오후에 랩에 들릴께.
그나저나 잘만들어뒀네 ㅎㅎ 굿잡!

**Comment by oryondark** [comment]
## 작업상황

*  CropImage 마다 원본 이미지의 이름이 출력되도록 수정했습니다.

---------------------
![image](https://user-images.githubusercontent.com/35071931/40472245-d7b6c562-5f73-11e8-9a32-63d712c118f7.png)
