### ISSUE TITLE
EC2 접속 문제 해결

### ISSUE THREAD

**Issue by kmu-leeky** [kmu-leeky/crc-research#6]
우선 SSH 를 22번 포트외에 다른 포트 번호에서 가능하게 하도록 하고
- https://askubuntu.com/questions/264046/how-to-ssh-on-a-port-other-than-22

AWS 에서 해당 포트를 열어주기
-  https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html

**Comment by oryondark** [comment]
감사합니다. 교수님 해결되었습니다!
SSH 포트를 일부로 막는 경우를 잘 유념해두도록 하겠습니다.

**Comment by kmu-leeky** [comment]
오케이. 학교 네트워크가 보안 문제로 22번은 in/out 모두 막아두는 경우가 많은듯

**Comment by wkim1986** [comment]
Change sshd Port on Mac OS
https://github.com/wkim1986/bigdata-study/issues/1
