### ISSUE TITLE
annotation 된 정보를 활용해서 원본이미지를 crop 하는 기능 구현

### ISSUE THREAD

**Issue by kmu-leeky** [kmu-leeky/crc-research#9]
현재 annotation 정보는 json 포맷으로만 저장 됨.
좌표 정보를 활용하여 실제로 이미지를 crop 하는 기능 구현 필요.

**Comment by wkim1986** [comment]
**1. Install OpenCV on Ubuntu**

$ sudo -s

# apt-get update
# apt-get install libssl-dev openssl
# apt-get install pkg-config
# apt-get install libgtk2.0-0
# apt-get install libgtk2.0-dev
# apt-get install libavformat-dev libswscale-dev
# apt-get install libjpeg-dev

# apt-get install cmake
# apt-get install gcc-4.3
# apt-get install build-essential

# cd -p opencv/release
# cd opencv/release

# cmake -D CMAKE_BUILD_TYPE=release -D CMAKE_INSTALL_PREFIX=/usr/local -D BUILD_PYTHON_SUPPORT=ON -D BUILD_EXAMPLES=ON ../
# make
# make install
# ldconfig
# export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
# ldconfig
=> $ echo $LD_LIBRARY_PATH
=> $ pkg-config --modversion opencv
=> $ pkg-config --libs --cflags opencvm

**2. Compile**
=> g++ -std=c++11 Sample.hpp Sample.cpp $(pkg-config --libs --cflags opencv)

**Comment by wkim1986** [comment]
**1. Download MacPorts**

http://www.macports.org/install.php

**2. Install OpenCV on Mac OS**

$ sudo port -v selfupdate
$ sudo port install subversion
$ sudo port install cmake

$ cd opencv

$ cmake -G "Unix Makefiles"
$ make -j8
$ sudo make install
$ sudo port install opencv
=> Headers:     /opt/local/include/opencv
=> Libraries:   /opt/local/lib/

**Comment by oryondark** [comment]
1차 작업 진행
----------------
1. python 을 이용한 image cropper 기능 1차 구현으로 현재 imageName_patternName_tagginCountNumber.jpg 형태로 파일을 저장하도록 구현.

ex) image1.json image1.jpg가 있을 때, image1.json이 여러가지 태깅값을 지니고 있다면, 아래와 같이 구현

![image](https://user-images.githubusercontent.com/35071931/38820843-e0077282-41d9-11e8-892f-de14a8a6eabc.png)

2. 현재 Json 데이터에 timestamp가 추가

**Comment by kmu-leeky** [comment]
superb! 오후에 얘기를 해보자.

**Comment by kmu-leeky** [comment]
저장 파일명은
원본이미지 파일이름_태깅정보_x좌표_y좌표_width_heigt_timestamp.jpg 저장.

**Comment by oryondark** [comment]
Crop 구현 1차 완료하였습니다.
-----------------
a) https://github.com/kmu-bigdata/annotorious/tree/kookmin-Labs

Issue
-------
태깅정보 추가 및 변경

**Comment by oryondark** [comment]
Crop 기능 구현 완료
-----------------------------
교수님
현재 javascript 패키지 및 입력된 xy좌표를 기준으로 crop하도록 기능을 수정하여 완료하였습니다.

Issue
------
처음 Cropping을 진행하면, empty 파일이 생성되는 현상이 있습니다.
